[general]
title = "Portfolio Indexa Test"

[input]
orders_file = "orders_indexa.csv"

[input.csv]
### Indexa columns
date    = 1     # Order date (operation)
isin    = 3     # ISIN (International Securities Identification Number)
subsc   = 4     # Type: SUSCRIPCIÓN/REEMBOLSO
shares  = 5     # Num of shares
amount  = 6     # Estimated total cost

### Format
date_format = "%Y-%m-%d"
delimiter = ";"
decimal_separator = ","

[cache]
price = ".price_cache.json"
price_ttl_hours = 12
historical = ".historical_cache.csv"
historical_max_age_days = 14
