[general]
title = "Portfolio MyInvestor Test"

[input]
orders_file = "orders_myinvestor.csv"

[input.csv]
## MyInvestor columns
date    = 0     # 0: Order date
isin    = 1     # 1: ISIN (International Securities Identification Number)
amount  = 2     # 2: Estimated total cost
shares  = 3     # 3: Num of shares

### Format
date_format = "%d/%m/%Y"
delimiter = ";"
decimal_separator = ","

[cache]
price = ".price_cache.json"
price_ttl_hours = 12
historical = ".historical_cache.csv"
historical_max_age_days = 14
